### ISSUE TITLE
Multiple emulator in same docker container

### ISSUE THREAD

**Issue by jessechen0319** [tracer0tong/android-emulator#14]
Hi Author,

it is possible to create several avd in the docker container manually and start them?
I tried the command in the entrypoint.sh, but failed.
`echo "no" | /usr/local/android-sdk/tools/android create avd -f -n test2 -t ${EMULATOR} --abi default/${ARCH}`
`echo "no" | /usr/local/android-sdk/tools/emulator64-${EMU} -avd test2 -noaudio -no-window -gpu off -verbose -qemu -usbdevice tablet -vnc :0`

**Comment by tracer0tong** [comment]
Technically its possible, but practically I think better to run second container. Each AVD will consume additional space and container size will grow significantly. Why do you want to run 2 AVDs?

**Comment by jessechen0319** [comment]
Hi Author,
Thank you for your reply.
I wonder if we can control the number of the emulator when executing "docker run".

**Comment by osvso** [comment]
That should be possible, but indeed the easiest and most flexible way to do that would be to run a separate docker image for every emulator. You also need to keep in mind that every emulator require a separate TCP port which need to be exposed. To make it fully automated you will to run some discovery service scanning ports on you running images and creating a mapping.

**Comment by tracer0tong** [comment]
I think I will close this issue, because I think it's more easy to run multiple containers.

**Comment by jessechen0319** [comment]
OK, Thank you author.
