### ISSUE TITLE
device offline

### ISSUE THREAD

**Issue by dapeng-fu** [tracer0tong/android-emulator#18]
Hi,

I just follow your introduction to install the emulator. But it shows device is offline after connected the emulator. Do you have meet this issue before ?
I've tried some ways to fix it, such as restart adb( adb kill-server & start-server) , delete .android/adbkey & adbkey.pub.    But none work...

**Comment by tracer0tong** [comment]
I will look on it, thank you for your message.

**Comment by tracer0tong** [comment]
Hi @dapeng-fu I have fixed problem. Emulator by itself works fine, but ADB instance took connection to emulator, thats why ADB outside container couldn't work with the same socket. Seems like this, I don't want to dig in details, but if you will upgrade to latest version or just simply kill ADB inside container it will work.
Thank you for your message again.

**Comment by dapeng-fu** [comment]
Thanks so much ! I'll try it right now.
