### ISSUE TITLE
QUESTION: add apk and files to the image

### ISSUE THREAD

**Issue by Heshyo** [tracer0tong/android-emulator#19]
I'm quite new to Docker and was wondering if it's possible to already install apks and add files to the emulator, and make a new image out of it, to avoid having to copy and reinstall things each time the container is started?

I tried doing a commit after adding apks and file, but when running the resulting image, no apk was installed and no file was there.

**Comment by tracer0tong** [comment]
Yes, you can build container with emulator, you even can put file inside container and install file to emulator, as one of Dockerfile lines, but my opinion that this is not very natural way to use Docker.
