### ISSUE TITLE
Old 32-bit version of Ubuntu used for image

### ISSUE THREAD

**Issue by tracer0tong** [tracer0tong/android-emulator#2]
To avoid problems with Android SDK 32-bit toolchain I've used 32-bit old Ubuntu. I should add 32-bit support to my image based on Ubuntu 14.04

**Comment by JixiaAAM** [comment]
I got your docker image of android emulator: tracer0tong/android-emulator  from github. I use it this way:
1)             $ docker pull tracer0tong/android-emulator:latest
2)             $ docker run -d -P --name android tracer0tong/android-emulator 
3)             $ docker ps –a 
I get:
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS                        PORTS                         NAMES
a5f9318c6496        tracer0tong/android-emulator   "/entrypoint.sh -e an"   25 minutes ago      Up 25 minutes                 0.0.0.0:32771->22/tcp, 0.0.0.0:32770->5554/tcp, 0.0.0.0:32769->5555/tcp, 0.0.0.0:32768->5900/tcp android
So, it seems working and it can provide adb ports. 
4)             $ adb connect 192.168.99.100:32769, it succeed
5)             $ adb devices. It failed, does not display any information
 
I tried to play with this image for 2 days, used different ways , but can’t make it work. 
I hope to get an android emulator that can support adb commands, so I can install software in it. And by using Appium, I can control this android emulator, just like I control android physical devices.
