### ISSUE TITLE
SSH permission denied, VNC denied

### ISSUE THREAD

**Issue by larsschwarz** [tracer0tong/android-emulator#20]
Running Docker on Windows 10, started with

`$ docker run -d -P --name android tracer0tong/android-emulator`

docker ps shows the container and available ports just fine.

```
$ docker ps
CONTAINER ID        IMAGE                          COMMAND             CREATED             STATUS              PORTS                                                                                                                       NAMES
a494f19f07a4        tracer0tong/android-emulator   "/entrypoint.sh"    32 minutes ago      Up 32 minutes       0.0.0.0:32772->22/tcp, 0.0.0.0:32771->5037/tcp, 0.0.0.0:32770->5554/tcp, 0.0.0.0:32769->5555/tcp, 0.0.0.0:32768->5900/tcp   android
```

When I try SSHing into it using user root it gives me "connection refused".

```
$ ssh root@0.0.0.0 -p 32722
ssh: connect to host 0.0.0.0 port 32722: Connection refused
```

Trying to connect via VNC (using RealVNC client and port 5900) it gives me "denied by remote host".

**Comment by larsschwarz** [comment]
Ok, seems the SSH issue can be solved by not using 0.0.0.0 but the Docker IP instead.

**Comment by tracer0tong** [comment]
You are right. There is a difference between Windows and Linux environments, Windows currently will run container in Oracle Virtual Box, that's why you should use another IP address.

Yury Leonychev

**Comment by larsschwarz** [comment]
Thanks, still can't connect to the VNC server though, I see the process running, but when trying to connect with a VNC client it's always refusing the connection. Might be a similar issue with Docker on Windows though and I'll close this "issue".
