### ISSUE TITLE
Can I config memory of the emulator? What is the default memory of the emulator?

### ISSUE THREAD

**Issue by Ming-Zhe** [tracer0tong/android-emulator#27]

**Comment by tracer0tong** [comment]
Please check startup script, it creates and starts VM with "emulator" command. You can check options in https://developer.android.com/studio/run/emulator-commandline.html Search for "-memory" on that page.

**Comment by Ming-Zhe** [comment]
@tracer0tong Thank you for your response. The startup script you mean "entrypoint.sh"?

**Comment by tracer0tong** [comment]
Yes, last lines of this file.

**Comment by Ming-Zhe** [comment]
Thank you, I will try.
