### ISSUE TITLE
Docker build hangs at "android update sdk --filter platform-tool --no-ui --force"

### ISSUE THREAD

**Issue by iam-peekay** [tracer0tong/android-emulator#6]
For some reason, the build just hangs. Do you happen to know what might cause this?

**Comment by tracer0tong** [comment]
Hi, @iam-peekay! I've the same issue on Windows. Could you provide version and architecture of OS where you using container?

**Comment by iam-peekay** [comment]
Hi. I am using it on Mac.
[image: Inline image 1]

On Mon, Jan 25, 2016 at 3:49 PM, Tracer Tong notifications@github.com
wrote:

> Hi, @iam-peekay https://github.com/iam-peekay! I've the same issue on
> Windows. Could you provide version and architecture of OS where you using
> container?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tracer0tong/android-emulator/issues/6#issuecomment-174734109
> .

## 

Preethi Kasireddy
201-895-9299
Twitter https://twitter.com/iam_preethi
LinkedIn https://www.linkedin.com/pub/preethi-kasireddy/28/835/413
Github https://github.com/iam-peekay
Facebook https://www.facebook.com/preethikasireddy

**Comment by tracer0tong** [comment]
Ok, could you also provide RAM amount and disk space amount of your Docker VM?

**Comment by iam-peekay** [comment]
Hi,

Where can i find this information? Happy to send it to you.

On Mon, Jan 25, 2016 at 4:08 PM, Tracer Tong notifications@github.com
wrote:

> Ok, could you also provide RAM amount and disk space amount of your Docker
> VM?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tracer0tong/android-emulator/issues/6#issuecomment-174739122
> .

## 

Preethi Kasireddy
201-895-9299
Twitter https://twitter.com/iam_preethi
LinkedIn https://www.linkedin.com/pub/preethi-kasireddy/28/835/413
Github https://github.com/iam-peekay
Facebook https://www.facebook.com/preethikasireddy

**Comment by tracer0tong** [comment]
Docker for Mac usually installs Oracle Virtual Box for supporting Docker VM. Please, find Oracle VirtualBox in Applications and check info about VM named "default".

**Comment by iam-peekay** [comment]
[image: Inline image 1]

On Mon, Jan 25, 2016 at 4:42 PM, Tracer Tong notifications@github.com
wrote:

> Docker for Mac usually installs Oracle Virtual Box for supporting Docker
> VM. Please, find Oracle VirtualBox in Applications and check info about VM
> named "default".
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tracer0tong/android-emulator/issues/6#issuecomment-174749224
> .

## 

Preethi Kasireddy
201-895-9299
Twitter https://twitter.com/iam_preethi
LinkedIn https://www.linkedin.com/pub/preethi-kasireddy/28/835/413
Github https://github.com/iam-peekay
Facebook https://www.facebook.com/preethikasireddy

**Comment by tracer0tong** [comment]
Unfortunately I've discovered that this is a related issue in Docker https://github.com/docker/docker/issues/18180 So, we just should wait for fix. I think that is the reason why everything works fine on my Linux server.

**Comment by tracer0tong** [comment]
@iam-peekay I recommend you to use some recipes from https://github.com/docker/docker/issues/18180

**Comment by iam-peekay** [comment]
Thanks @tracer0tong. Although I installed the new Docker fix, it still hangs. It seems to be something with installing the android platform tools. Here's the output for more info:

![image](https://cloud.githubusercontent.com/assets/5421194/12661525/ec445f1c-c5ce-11e5-9946-bc2d8e53210b.png)

**Comment by tracer0tong** [comment]
Looks like you have no free space in Docker VM. Try not to build. Clean old
images and than just make docker run tracer0tong/android-emulator:latest.
I've uploaded new version to dockerhub.

On Friday, 29 January 2016, Preethi Kasireddy notifications@github.com
wrote:

> Thanks @tracer0tong https://github.com/tracer0tong. Although I
> installed the new Docker fix, it still hangs. It seems to be something with
> installing the android platform tools. Here's the output for more info:
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/5421194/12661525/ec445f1c-c5ce-11e5-9946-bc2d8e53210b.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tracer0tong/android-emulator/issues/6#issuecomment-176468900
> .

## 

Kind regards,
Yury Leonychev yuriy.leonychev@gmail.com yuriy.leonychev@gmail.com

**Comment by iam-peekay** [comment]
@tracer0tong Got it. I guess my issue is I plan to add a faster vnc server to the emulator, so just need to add a few more lines to your Dockerfile and entryfile. 

In any case, I know the emulator comes with a built-in vnc server which I can try out temporarily. if I were to just run your image, do you think you can point me to where I can look to find what port # I can connect to the vnc server on?  

Thank you in advance.

**Comment by tracer0tong** [comment]
You can see 5900 port exposed to outside. Connect to this port with any VNC client and you could see emulator screen. Unfortunately stock android emulator VNC couldn't get mouse movements. So, if you want to interact with emulator, you should install you own VNC server. Anyways I expose SSH to emulator, VNC and ADB ports, that provides all available emulator functions.

**Comment by tracer0tong** [comment]
I've recommend to install any VNC server via ADB connection if you want to interact manually with device.

**Comment by iam-peekay** [comment]
@tracer0tong got it. thank you! yes, that's what im thinking

**Comment by iam-peekay** [comment]
@tracer0tong if you've seen any implementations or examples of installing VNC server via ADB connection, please let me know!

**Comment by tracer0tong** [comment]
May be you can try this app https://play.google.com/store/apps/details?id=com.pranayc.remotevncserver
Not sure, I'd prefer automation and interaction with device via Android monkeyrunner.

**Comment by iam-peekay** [comment]
@tracer0tong thank you! A quick question: in order to connect to the emulator on port 5900 from a VNC client, what is the ip address I use? localhost doesn't work

**Comment by tracer0tong** [comment]
The same ip address as for ADB connection. Just check ip address in
Kitematic settings.

On Sat, Jan 30, 2016 at 6:45 AM, Preethi Kasireddy <notifications@github.com

> wrote:
> 
> @tracer0tong https://github.com/tracer0tong thank you! A quick
> question: in order to connect to the emulator on port 5900 from a VNC
> client, what is the ip address I use? localhost doesn't work
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tracer0tong/android-emulator/issues/6#issuecomment-176982588
> .

## 

Kind regards,
Yury Leonychev yuriy.leonychev@gmail.com yuriy.leonychev@gmail.com
