### ISSUE TITLE
Operation times out when trying to connect to server

### ISSUE THREAD

**Issue by iam-peekay** [tracer0tong/android-emulator#7]
I tried both the 0.0.0.0 IP address and 171.17.0.2 IP address, but the connection either times out or is refused. Any help would be appreciated.

![image](https://cloud.githubusercontent.com/assets/5421194/12690076/d427e760-c695-11e5-9542-6095c57978cc.png)

**Comment by iam-peekay** [comment]
@tracer0tong I'm going to close this issue, as it worked when I connected it using the IP address Kinematic provides. Perhaps worth adding to a note on this to the docs?

Thanks again for the help!

**Comment by tracer0tong** [comment]
Thank, you for your comment! I will add this to docs. Problem that most native way to run docker - Linux machine and command line, so all intermediate VMs (as Kitematic) will add second abstraction level with another ip-addresses.

**Comment by iam-peekay** [comment]
@tracer0tong yes, exactly! This concept is pretty confusing for mac/windows users just getting into Docker (like myself). I finally figured out the abstraction layers, but having a small note for Max users in the docs might help someone who is just getting started. 

Thanks for all the help!

**Comment by tracer0tong** [comment]
I've fix Readme, so you can support project with likes/stars on Dockerhub and Github =)

**Comment by iam-peekay** [comment]
@tracer0tong done!

**Comment by tracer0tong** [comment]
And again, thank you for feedback, because it gives a chance to look on project from other side.
